version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - "8001:5000"
    volumes:
      - .:/srv
    depends_on:
      - db
    networks:
      - main-internal-net
      - admin-shared-net
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
    networks:
      - main-internal-net
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
    networks:
      - main-internal-net

networks:
  main-internal-net:
  admin-shared-net:
    external: true #needs to be created by other file
    name: shared-docker-network